# Use the official OpenJDK 11 base image
FROM openjdk:11-jdk

# Update package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y wget unzip vim telnet mariadb-client jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a directory for Tomcat
RUN mkdir -p /opt/tomcat

# Download and extract Apache Tomcat 8.5
RUN wget -q https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.tar.gz -O /tmp/tomcat.tar.gz && \
    tar xzf /tmp/tomcat.tar.gz -C /opt/tomcat --strip-components=1 && \
    rm /tmp/tomcat.tar.gz

RUN rm /opt/tomcat/conf/tomcat-users.xml /opt/tomcat/webapps/manager/META-INF/context.xml

# Copy your .war artifact to Tomcat webapps directory
COPY target/dptweb-1.0.war /opt/tomcat/webapps/
COPY tomcat-users.xml /opt/tomcat/conf/tomcat-users.xml
COPY context.xml /opt/tomcat/webapps/manager/META-INF/context.xml

# Expose the default Tomcat port
EXPOSE 8080

# Start Tomcat on container runtime
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
